services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d url-shortener']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    env_file:
      - docker.env
    depends_on:
      postgres:
        condition: service_healthy
