services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    env_file:
      - .env.production
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.production
    depends_on:
      postgres:
        condition: service_healthy
